# Site settings
title: Logic Automation Design
email: info@LogicAutomationDesign.com
url: https://LogicAutomationDesign.com
description: "Logic Automation Design - Your source for automation control parts and solutions. Find high-quality used parts and custom aftermarket solutions for your unique needs. Explore now."
keywords: "Automation Parts and Design"
skills: "Powerful Results"
meta_author: Logic Automation Design

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0072c6 #0072C6
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Logic Automation Design
  credits: Used Equipement
  social: Follow us
  location: Location

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url: http://facebook.com/
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: bitbucket
    url: http://bitbucket.org/
  - title: linkedin
    url: http://linkedin.com/

# Credits content
credits: 'Please feel free to contact us with a detailed list of parts if you have equipment you want to sell.'

# Postal address (add as many lines as necessary)
address:
  - line: Oakville
  - line: Ontario, Canada

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
